Portfolio Accessibility
ausiemass/portfolio-austin pull request #9
Opened 2023-06-19 23:47 UTC by ausiemass

In this project, accessibility of my portfolio was checked. The following issues were discovered:

#Page titles
The title should be changed to Austin's portfolio home. Current code is shown on the link below.
https://github.com/ausiemass/portfolio-austin/blob/54e1c6e1807b87b186e88c7e6f451772a3a5ec23/index.html#LL7C1-L7C28

#Image text alternatives** (<img alt="alt text">)

All the images have alt text. However, some of the text does not explain the images they represent.  Current code is shown on the link below.
https://github.com/ausiemass/portfolio-austin/blob/54e1c6e1807b87b186e88c7e6f451772a3a5ec23/index.html#LL51C3-L51C95

#Text headings

No issues found.

#Color contrast

 There is a very low contrast between text and background color for 17 texts with color code #6070ff on white background. Current code is shown on the link below.

 https://github.com/ausiemass/portfolio-austin/blob/54e1c6e1807b87b186e88c7e6f451772a3a5ec23/styles.css#LL34C1-L34C18

#Resize

 At 200% zoom, horizontal bar is visible.

#Interaction (labels are optional but recommended as voiceover tools can read them, and should be set as invisible to match the Figma design)

Form input fields like name, email adress and textarea, do not have labels. 

#Moving content

no issues found

#Multimedia
no issues found

#The basic structure of the page

when styles and images are disabled, the information makes sense when read in the order it is shown. However, some of the alt text do not provide adequate information for the missing images. descriptive text was updated in this PR. Current code is shown on the link below.

https://github.com/ausiemass/portfolio-austin/blob/54e1c6e1807b87b186e88c7e6f451772a3a5ec23/index.html#LL77C1-L77C108

https://github.com/ausiemass/portfolio-austin/blob/54e1c6e1807b87b186e88c7e6f451772a3a5ec23/index.html#LL103C1-L103C107

https://github.com/ausiemass/portfolio-austin/blob/54e1c6e1807b87b186e88c7e6f451772a3a5ec23/index.html#L129

2023-06-19 23:57 UTC, LionRouge1 reviewed
Hi @ausiemass, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that was supposed to be a pair-programming activity but you're the only one who contributed to the project. Kindly work with your partner to submit this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-20 18:41 UTC, Alusp requested changes
Hi @ausiemass , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
 
![close](https://media.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- [ ] Good Commit History :green_circle: 
- [ ] Good Github Flow :green_circle: 
- [ ] Good PR Summary :green_circle: 
- [ ] No Linter Errors :green_circle: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] A very good job so far :+1: However, Please use this [link] to resolve your contrast as its showing 17 contrast errors.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 18:41 UTC, Alusp commented on index.html
> `<p class="myself">About Myself </p>`

- [ ] Good job in implementing the changes for accessibility, However, Please replace the `<p>` tag `<h2>` tag as its suppose to be a heading not a paragraph as given in the requirement. :slightly_smiling_face:

2023-06-20 18:41 UTC, Alusp commented on index.html
> `<input class="form-item input-item" type="text" maxlength="30" placeholder="Lorem Ipsum" required>
     <input class="form-item input-item" type="email" placeholder="loremipsum@gmail.com" required>
     <textarea class="form-item input-item" name="comment" id="comment" cols="50" rows="10" maxlength="500" placeholder="Write your message here..." required></textarea>`

- [ ] A very good job here so far :clap: However, Please add a label to each of the form input field as recommended in the project requirement. Kindly use this [link](https://www.w3schools.com/tags/tag_label.asp) for quick reference on how to implement it. :slightly_smiling_face:

2023-06-20 18:41 UTC, Alusp commented on index.html
> `<span class="skills">Languages <span><img class="skills-img1" src="./images/arrowDown.jpg" alt="languages"></span></span>`

- [ ] A very good job here so far :+1: However, Please use another name for your alt text because the word `languages` is redundant. below is the screenshot of the error message. 

![redundant](https://github.com/ausiemass/portfolio-austin/assets/43528594/c3fba3ce-3373-4c78-b236-c1524b982218)

2023-06-20 22:37 UTC, santitoot commented
The "link" you refer to is not referenced, could you send it again, please?

2023-06-21 03:54 UTC, Alusp commented
Hello @santitoot, here is the [link](https://wave.webaim.org/), this link is very helpful  in guiding you on your page accessibility. it will show you all your errors, please pay attention on the red errors only as those are the essential ones.

2023-06-22 16:15 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @ausiemass , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Good design
✅ ... Green linters

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 20:46 UTC, merged